name: ESLint

on: push

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn workspace @dao-interface/webapp install
      - name: Run ESLint
        run: yarn workspace @dao-interface/webapp lint
