name: Jest and Codecov

on: push

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn workspace @dao-interface/webapp install
      - name: Run Jest
        run: yarn workspace @dao-interface/webapp test
      - name: Run Codecov
        run: yarn workspace @dao-interface/webapp codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
